nome = input('Qual o seu nome ?')
print(nome, 'Seja Muito Bem Vindo')
dia = input('Qual foi o dia do seu nascimento')
mes = input('Qual foi o mes de seu nascimento')
ano = input('Qual foi o ano de seu nascimento')
print( dia + '/' + mes + '/' + ano)
Numero_um = input('Digite um numero')
Numero_dois = input('Digite o segundo numero')
soma = int(Numero_um + Numero_dois)
print(soma)
print("A soma dos numeros é:", soma)
